sudo: false
language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

git:
  depth: 1

notifications:
  email: false

script: npm test

# Enable this when we want to publish v1.0.0
# after_success: npm run semantic-release -s
